### PR TITLE
Revert "udp: improve handling of network errors"

### PR DESCRIPTION
**Pull request by g-arjones**
Reverts rock-core/drivers-iodrivers_base#39

That PR broke multiple components that depend on the library (including drivers/orogen/iodrivers_base). I propose we revert until one of us can investigate further

### CODE REVIEW

**Comment by doudou** [comment]
> That PR broke multiple components that depend on the library (including drivers/orogen/iodrivers_base). I propose we revert until one of us can investigate further

Can you give me more details ? I haven't had any problem, neither did the CI. I just checked, and we went through all the unit tests of all the drivers we have here. Some unit tests even use UDP.

**Comment by g-arjones** [comment]
```console
squidbot@arjones-eos:~/dev/squidbot/drivers/iodrivers_base$ git rev-parse HEAD
cc3fd2dd1c455b82c81da0b32649158643372593
squidbot@arjones-eos:~/dev/squidbot/drivers/iodrivers_base$ amake
  operating system: ubuntu,debian - 18.04,18.04.3,lts,bionic,beaver
  typelib: using the castxml importer
  environment already up-to-date
Command finished successfully at 2020-10-23 12:21:43 -0300 (took 10 secs)
squidbot@arjones-eos:~/dev/squidbot/drivers/iodrivers_base$ cd ../orogen/iodrivers_base
squidbot@arjones-eos:~/dev/squidbot/drivers/orogen/iodrivers_base$ amake
  operating system: ubuntu,debian - 18.04,18.04.3,lts,bionic,beaver
  typelib: using the castxml importer
  environment already up-to-date
Command finished successfully at 2020-10-23 12:21:43 -0300 (took 10 secs)
squidbot@arjones-eos:~/dev/squidbot/drivers/orogen/iodrivers_base$ syskit orogen-test test/iodrivers_base_test.rb --workdir build/bundle --name="/calls processIO repeatedly until all data has been read/"
Roby[WARN]: debugging is disabled because the 'pry' gem cannot be loaded
Test logs are saved in /home/squidbot/dev/squidbot/drivers/orogen/iodrivers_base/build/bundle/logs/20201023-1225.1
default[WARN]: there is already a constant with the nameOroGen::IodriversBase::Test, I am not registering the modelfor iodrivers_base::test::PeriodicTask there
Run options: "--name=/calls processIO repeatedly until all data has been read/" --seed 6012

# Running:

E.E

Finished in 1.531147s, 1.9593 runs/s, 7.1842 assertions/s.

  1) Error:
OroGen.iodrivers_base.Task::the behavior of FD-driven activities#test_0003_calls processIO repeatedly until all data has been read:
Roby::Test::ExecutionExpectations::UnexpectedErrors: 1 unexpected errors
[1/1] from OroGen.iodrivers_base.test.FDTask:0x560d46dc2298<id:68>(conf: ["default"], orocos_name: task_under_test) with trace 
  Exception:
    mission failed: OroGen.iodrivers_base.test.FDTask:0x560d46dc2298
      no owners
      arguments: 
        orocos_name: "task_under_test",
        conf: ["default"]
    event 'exception' emitted at [12:25:48.672 @2532] from
      OroGen.iodrivers_base.test.FDTask:0x560d46dc2298
        no owners
        arguments: 
          orocos_name: "task_under_test",
          conf: ["default"]
    /home/squidbot/dev/squidbot/drivers/orogen/iodrivers_base/test/iodrivers_base_test.rb:52:in `block (3 levels) in <top (required)>'

  2) Error:
OroGen.iodrivers_base.Task::the behavior on non FD-driven activities::with a file descriptor#test_0003_calls processIO repeatedly until all data has been read:
Roby::Test::ExecutionExpectations::UnexpectedErrors: 1 unexpected errors
[1/1] from OroGen.iodrivers_base.test.PeriodicTask:0x560d483af7b8<id:376>(conf: ["default"], orocos_name: task_under_test) with trace 
  Exception:
    mission failed: OroGen.iodrivers_base.test.PeriodicTask:0x560d483af7b8
      no owners
      arguments: 
        orocos_name: "task_under_test",
        conf: ["default"]
    event 'exception' emitted at [12:25:49.592 @6777] from
      OroGen.iodrivers_base.test.PeriodicTask:0x560d483af7b8
        no owners
        arguments: 
          orocos_name: "task_under_test",
          conf: ["default"]
    /home/squidbot/dev/squidbot/drivers/orogen/iodrivers_base/test/iodrivers_base_test.rb:92:in `block (4 levels) in <top (required)>'

3 runs, 11 assertions, 0 failures, 2 errors, 0 skips
squidbot@arjones-eos:~/dev/squidbot/drivers/orogen/iodrivers_base$ cd build/bundle/logs/current
squidbot@arjones-eos:~/dev/squidbot/drivers/orogen/iodrivers_base/build/bundle/logs/current$ more task_under_test* | cat
::::::::::::::
task_under_test-1529.txt
::::::::::::::
0.284 [ ERROR  ][OrbRunner] in updateHook(): switching to exception state because of unhandled exception
0.284 [ ERROR  ][OrbRunner]   readPacket(): no data waiting for data. Last wait lasted 99ms, out of a total wait of 100ms
::::::::::::::
task_under_test-1559.txt
::::::::::::::
::::::::::::::
task_under_test-1586.txt
::::::::::::::
0.229 [ ERROR  ][OrbRunner] in updateHook(): switching to exception state because of unhandled exception
0.229 [ ERROR  ][OrbRunner]   readPacket(): no data waiting for data. Last wait lasted 99ms, out of a total wait of 100ms
```

**Comment by g-arjones** [comment]
It fails in our CI as well, btw...

**Comment by doudou** [comment]
And it does not on our. That's the annoying bugs .... It does fail on my machine, I'm looking into it.

Can you try [this branch](https://github.com/rock-core/drivers-orogen-iodrivers_base/pull/new/always_use_waitread) ?

**Comment by doudou** [comment]
It's the change to waitRead. Trying to find out why ...

**Comment by doudou** [comment]
(the change to waitRead made me realize that some change was needed on orogen/iodrivers_base as well, but it should not have changed behavior)

**Comment by g-arjones** [comment]
> It's the change to waitRead. Trying to find out why ...

I'm curious about why it didn't fail in your CI... It fails pretty consistently here

**Comment by doudou** [comment]
> I'm curious about why it didn't fail in your CI... It fails pretty consistently here

That would be because the tests of `drivers/orogen/iodrivers_base` were disabled :(

**Comment by doudou** [comment]
Btw, when you find something like that in a core package, revert first, ask questions later. I do trust your judgement.

**Comment by g-arjones** [comment]
Will do.

> I do trust your judgement.

Thanks ;)

**Pull request merged**
