### PR TITLE
create a harness to test drivers as blackboxes

### PR DESCRIPTION
**Pull request by doudou**
This uses a stream object (TestStream) that gives direct access
to writing and reading data to/from the driver. A driver can be
initialized with a TestStream as main stream by using the test://
URI, thus allowing to pass through the driver's own open methods.

### CODE REVIEW

**Comment by g-arjones** [comment]
This is nice to have... But, a lot of code just to avoid using a socketpair() + setFileDescriptor() during tests. Or are there any other advantages that I am missing?

**Comment by doudou** [comment]
> Or are there any other advantages that I am missing?

Sockets or pipes are asynchronous, and have limited internal buffers. You would need to have timing issues (what's a good timeout so that the test passes as expected, but that is not too long as to make the tests take forever ?). Make sure on the write side that you don't go over buffers (more load on the test writer). Moreover, you don't control exactly what the driver will read (it might read byte-by-byte while you wanted it to read 3 bytes in a row, all of it is timing-dependent).

Also, most of the code is not related to the feature itself, but really to streamline the tests themselves (the fixture stuff). The stream class is really small.

About the choice of a test:// URI: setFileDescriptor (or setMainStream done externally) do not allow you to go through the driver's own open logic while the test:// URI does.

**Comment by g-arjones** [comment]
> Sockets or pipes are asynchronous, and have limited internal buffers. You would need to have timing issues (what's a good timeout so that the test passes as expected, but that is not too long as to make the tests take forever ?).

Set the fds as blocking and you don't have to worry about this.

> Moreover, you don't control exactly what the driver will read (it might read byte-by-byte while you wanted it to read 3 bytes in a row, all of it is timing-dependent).

socketpair() with SOCK_DGRAM as the type will give you the framing behavior of UDP, AFAIK.

> Also, most of the code is not related to the feature itself, but really to streamline the tests themselves (the fixture stuff). The stream class is really small.
>
> About the choice of a test:// URI: setFileDescriptor (or setMainStream done externally) do not allow you to go through the driver's own open logic while the test:// URI does.

Fair enough (even though the open logic should have and probably do have their own separate tests). I like it! :)

**Comment by doudou** [comment]
> Set the fds as blocking and you don't have to worry about this.

The fds *are* blocking already in iodrivers_base. However, iodrivers_base whole design is to NEVER block the caller indefinitely.

Let's assume that I want to test "the driver keeps bytes if it has a partial packet" (common occurence), I would do

~~~
uint8_t msg[] = { 0, 2, 3 };
pushDataToDriver(msg, msg + 3);
ASSERT_THROW(TimeoutError, readPacket());
ASSERT_EQ(3, getQueuedBytes());
~~~

Now, if I use a socket, there is a timing between the test (writing) and the driver (reading). I must have some non-zero timeout to guarantee that the readPacket actually has the data ready to write. What's a good one ? I definitely don't want it to be too low, but then - since the test is expecting the timeout, it will take at least as much as the timeout to run ... so I definitely don't want to be too long.

> Fair enough (even though the open logic should have and probably do have their own separate tests). I like it! :)

Separate tests ... but those would also probably rely on communication with the driver. I'm guessing that as some point not-so-far-in-the-future I would have to extend this so that the test can get called back when data is written from the driver to allow for more "interactivity" as e.g. testing command-and-wait-for-reply methods - something also easy to do with this design.

**Comment by g-arjones** [comment]
Sounds good... 👍

**Pull request merged**
