### PR TITLE
add iodrivers_base_cat to display a data stream

### PR DESCRIPTION
**Pull request by doudou**
The display is in hex/ascii format, like e.g. hexdump

~~~
38 3a 3e 31 30 30 34 4c   72 51 71 55 6a 73 46 51   3a 6d 36 6b 50 30 44 4d   8:>1004L rQqUjsFQ :m6kP0DM
3a 2c 30 2a 35 43 0d 0a   21 41 49 56 44 4d 2c 31   2c 31 2c 2c 41 2c 42 3a   :,0*5C.. !AIVDM,1 ,1,,A,B:
55 38 43 53 50 30 30 47   3e 53 6e 3c 4c 66 56 4a   3e 3e 43 77 71 55 57 50   U8CSP00G >Sn<LfVJ >>CwqUWP
~~~

### CODE REVIEW

**Comment by g-arjones** [comment]
There are so many tools for this already..

**Comment by doudou** [comment]
> There are so many tools for this already..

I don't mind not merging this. But I don't know any for serial, that are command-line,
easily setup the serial port and display it in hex ?

**Comment by g-arjones** [comment]
```console
$ apt install socat
$ socat -xd /dev/ttyUSB0,b115200,raw -
...
```

**Comment by doudou** [comment]
> ```
> $ apt install socat
> $ socat -xd /dev/ttyUSB0,b115200,raw -
> ...
> ```

socat=cool ... Last debug I forwarded a RS485 stream to a netcat via udp and listened with wireshark. Hardly a very nice workflow.

I'm still going to merge this anyways ... will save hours of my life not having to read socat's manpage each single time I'll need it. But that's the last one, I promise.

**Comment by g-arjones** [comment]
> Last debug I forwarded a RS485 stream to a netcat via udp and listened with wireshark

Pretty cool indeed..

> I'm still going to merge this anyways

Sure :+1:

**Comment by doudou** [comment]
FYI ... added mention of the CLI tools and of socat in the README

**Pull request merged**
